Changed a few things for linux-x64 and started to get d-apps working again (not finished)

diff --git a/drivers/Makefile b/drivers/Makefile
--- a/drivers/Makefile
+++ b/drivers/Makefile
@@ -4,10 +4,10 @@ DIRS = $(filter-out $(wildcard *.*) Makefile,$(wildcard *))
 
 all:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -s --no-print-directory -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -s --no-print-directory -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done;
 
 clean:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -s --no-print-directory -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -s --no-print-directory -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done
diff --git a/lib/Makefile b/lib/Makefile
--- a/lib/Makefile
+++ b/lib/Makefile
@@ -1,15 +1,14 @@
-# TODO
-DIRS = c g m cpp gui shell vbe vterm
+DIRS = c g m cpp d gui shell vbe vterm
 
 .PHONY:  all clean
 
 all:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done
 
 clean:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done
 		rm -f *~
diff --git a/user/Makefile b/user/Makefile
--- a/user/Makefile
+++ b/user/Makefile
@@ -1,15 +1,14 @@
-# TODO
-DIRS = $(filter-out $(wildcard *.*) d Makefile,$(wildcard *))
+DIRS = $(filter-out $(wildcard *.*) Makefile,$(wildcard *))
 
 .PHONY:  all clean
 
 all:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -C $$i all || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done
 
 clean:
 		@for i in $(DIRS) ; do \
-			$(MAKE) $(JOBS) -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
+			$(MAKE) -C $$i clean || { echo "Make: Error (`pwd`)"; exit 1; } ; \
 		done
 		rm -f *~
